select
    interaction_id,
    cast(interaction_date as DATE) as interaction_date,
    cast(process_date as DATE) as process_date,
    customer_id,
    agent_id,
    interaction_type,
    channel,
    reason_category,
    cast(duration_seconds as DOUBLE) as duration_seconds,
    cast(wait_time_seconds as DOUBLE) as wait_time_seconds,
    cast(was_resolved as BOOLEAN) as was_resolved,
    cast(requires_followup as BOOLEAN) as requires_followup,
    detected_sentiment,
    cast(sentiment_score as DOUBLE) as sentiment_score,
    customer_detected_accent,
    agent_used_accent,
    cast(was_escalated as BOOLEAN) as was_escalated,
    mentioned_products,
    cast(has_transcript as BOOLEAN) as has_transcript,
    cast(has_recording as BOOLEAN) as has_recording,
    _source_file,
    cast(_ingested_at as TIMESTAMP) as _ingested_at
from {{ input_parquet('validated/call_center_interactions/part.parquet') }}
