select
    branch_id,
    branch_code,
    branch_name,
    branch_type,
    address,
    city,
    state,
    country,
    postal_code,
    geographic_zone,
    phone,
    email,
    opening_time,
    closing_time,
    cast(has_atms as BOOLEAN) as has_atms,
    cast(atm_count as DOUBLE) as atm_count,
    cast(has_teller_windows as BOOLEAN) as has_teller_windows,
    cast(teller_window_count as DOUBLE) as teller_window_count,
    cast(latitude as DOUBLE) as latitude,
    cast(longitude as DOUBLE) as longitude,
    cast(branch_opening_date as DATE) as branch_opening_date,
    branch_status,
    _source_file,
    cast(_ingested_at as TIMESTAMP) as _ingested_at
from {{ input_parquet('validated/branches/part.parquet') }}
