select
    survey_id,
    cast(survey_date as DATE) as survey_date,
    cast(process_date as DATE) as process_date,
    interaction_id,
    customer_id,
    agent_id,
    survey_type,
    send_channel,
    cast(main_score as DOUBLE) as main_score,
    nps_category,
    question_1_text,
    question_1_response,
    question_2_text,
    question_2_response,
    question_3_text,
    question_3_response,
    open_comments,
    comment_sentiment,
    cast(response_time_hours as DOUBLE) as response_time_hours,
    cast(campaign_response_rate as DOUBLE) as campaign_response_rate,
    _source_file,
    cast(_ingested_at as TIMESTAMP) as _ingested_at
from {{ input_parquet('validated/satisfaction_surveys/part.parquet') }}
