select
    event_id,
    cast(event_date as DATE) as event_date,
    cast(process_date as DATE) as process_date,
    customer_id,
    session_id,
    event_type,
    event_category,
    channel,
    platform,
    browser,
    app_version,
    page_url,
    page_title,
    action,
    element_id,
    product_id,
    cast(event_value as DOUBLE) as event_value,
    cast(duration_seconds as DOUBLE) as duration_seconds,
    ip_address,
    ip_country,
    ip_city,
    cast(is_mobile as BOOLEAN) as is_mobile,
    referrer,
    utm_source,
    utm_medium,
    utm_campaign,
    _source_file,
    cast(_ingested_at as TIMESTAMP) as _ingested_at
from {{ input_parquet('validated/digital_events/part.parquet') }}
