select
    complaint_id,
    cast(creation_date as DATE) as creation_date,
    cast(process_date as DATE) as process_date,
    customer_id,
    case_type,
    category,
    subcategory,
    reception_channel,
    affected_product_id,
    related_branch_id,
    cast(origin_interaction_id as VARCHAR) as origin_interaction_id,
    description,
    cast(claimed_amount as DOUBLE) as claimed_amount,
    currency,
    priority,
    status,
    assigned_agent_id,
    cast(assignment_date as DATE) as assignment_date,
    cast(first_response_date as DATE) as first_response_date,
    cast(resolution_date as DATE) as resolution_date,
    cast(closing_date as DATE) as closing_date,
    cast(sla_breached as BOOLEAN) as sla_breached,
    cast(resolution_days as DOUBLE) as resolution_days,
    resolution,
    cast(compensation_granted as DOUBLE) as compensation_granted,
    cast(resolution_satisfaction as DOUBLE) as resolution_satisfaction,
    cast(is_repeat_complainer as BOOLEAN) as is_repeat_complainer,
    _source_file,
    cast(_ingested_at as TIMESTAMP) as _ingested_at
from {{ input_parquet('validated/complaints/part.parquet') }}
