select
    send_id,
    cast(send_date as DATE) as send_date,
    cast(process_date as DATE) as process_date,
    campaign_id,
    customer_id,
    send_channel,
    template_used,
    subject,
    send_status,
    cast(was_delivered as BOOLEAN) as was_delivered,
    cast(was_opened as BOOLEAN) as was_opened,
    cast(open_date as DATE) as open_date,
    cast(was_clicked as BOOLEAN) as was_clicked,
    cast(click_date as DATE) as click_date,
    cast(click_count as DOUBLE) as click_count,
    cast(had_conversion as BOOLEAN) as had_conversion,
    cast(conversion_date as DATE) as conversion_date,
    cast(conversion_value as DOUBLE) as conversion_value,
    open_device,
    open_country,
    failure_reason,
    cast(send_cost as DOUBLE) as send_cost,
    _source_file,
    cast(_ingested_at as TIMESTAMP) as _ingested_at
from {{ input_parquet('validated/campaign_sends/part.parquet') }}
