select
    customer_id,
    document_number,
    document_type,
    first_name,
    last_name,
    date_of_birth,
    gender,
    email,
    mobile_phone,
    landline_phone,
    address,
    city,
    state,
    country,
    postal_code,
    detected_accent,
    segment,
    cast(credit_score as DOUBLE) as credit_score,
    cast(estimated_monthly_income as DOUBLE) as estimated_monthly_income,
    occupation,
    marital_status,
    education_level,
    cast(registration_date as DATE) as registration_date,
    registration_branch_id,
    customer_status,
    cast(last_updated as TIMESTAMP) as last_updated,
    cast(accepts_marketing as BOOLEAN) as accepts_marketing,
    _source_file,
    cast(_ingested_at as TIMESTAMP) as _ingested_at
from {{ input_parquet('validated/customers/part.parquet') }}
