select
    transaction_id,
    cast(transaction_date as DATE) as transaction_date,
    cast(process_date as DATE) as process_date,
    product_id,
    customer_id,
    case transaction_type when 'Deposit' then 'Depósito' when 'Withdrawal' then 'Retiro' when 'Payment' then 'Pago' when 'Purchase' then 'Compra' when 'Transfer' then 'Transferencia' when 'Adjustment' then 'Ajuste' when 'Depósito' then 'Depósito' when 'Retiro' then 'Retiro' when 'Pago' then 'Pago' when 'Compra' then 'Compra' when 'Transferencia' then 'Transferencia' when 'Ajuste' then 'Ajuste' end as transaction_type,
    transaction_category,
    cast(amount as DOUBLE) as amount,
    currency,
    cast(amount_usd as DOUBLE) as amount_usd,
    channel,
    branch_id,
    merchant_name,
    merchant_category,
    transaction_country,
    transaction_city,
    transaction_status,
    response_code,
    cast(is_fraud as BOOLEAN) as is_fraud,
    cast(fraud_score as DOUBLE) as fraud_score,
    cast(latitude as DOUBLE) as latitude,
    cast(longitude as DOUBLE) as longitude,
    _source_file,
    cast(_ingested_at as TIMESTAMP) as _ingested_at
from {{ input_parquet('validated/transactions/part.parquet') }}
